import "@styles/globals.css";
import type { Metadata } from "next";
import { Nav } from "@components/navBar";
import { Geist, Geist_Mono, Inter, Manrope } from "next/font/google";
import SubNavBar from "@components/subNavBar/SubNavBar";
import TertiaryNavBar from "@components/TertiaryNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

const manrope = Manrope({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-manrope'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${manrope.variable} antialiased`}
      >
        <Nav />
        <SubNavBar/>
        <TertiaryNavBar/>
        {children}
      </body>
    </html>
  );
}
