import "@styles/globals.css";
import type { Metadata } from "next";
import { Nav } from "@components/navBar";
import Footer from "@components/Footer/Footer";
import SubNavBar from "@components/subNavBar/SubNavBar";
import TertiaryNavBar from "@components/TertiaryNavBar";
import { Geist, Geist_Mono, Inter, Manrope, Dancing_Script, Lato, Poppins, Roboto } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

const manrope = Manrope({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-manrope'
})

const dancing_script = Dancing_Script({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dancing_script'
})

const lato = Lato({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato'
})

const poppins = Poppins({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins'
})

const roboto = Roboto({
  weight: ['100', '300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${manrope.variable} ${dancing_script.variable} ${lato.variable} ${poppins.variable} ${roboto.variable} antialiased`}
      >
        <Nav />
        <SubNavBar />
        <TertiaryNavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
